#!/usr/bin/env bash
set -eu
VERSION=$1
 REPO=$2
GROUP_ID=$3
ARTIFACT_ID=$4
TYPE=$5
SERVER=http://sfdfds.serv.dfd.dfdfsd:8081
 	
downloadUrl=$(curl -s -H "Authorization: Basic ERYDFSWYWRtaW4xMjM=" -X GET "${SERVER}/service/rest/v1/search/assets?repository=${REPO}&group=${GROUP_ID}&name=${ARTIFACT_ID}&version=${VERSION}&maven.extension=${TYPE}" | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["items"][0]["downloadUrl"]')

	
wget $downloadUrl -P /opt/app/svm/install
